// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSMMnsBL20NkievifMo0T1tLvizGSDj4c',
    appId: '1:196627223703:android:52ec7e85904fc1adc5c5d2',
    messagingSenderId: '196627223703',
    projectId: 'us-app-4bf30',
    storageBucket: 'us-app-4bf30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQaGlapfxHVRo0aVriq-cZ3TgVzN-3ra8',
    appId: '1:196627223703:ios:ec8c03320d834b2fc5c5d2',
    messagingSenderId: '196627223703',
    projectId: 'us-app-4bf30',
    storageBucket: 'us-app-4bf30.firebasestorage.app',
    iosBundleId: 'com.us.app.usApp',
  );

  // macOS reuses the iOS config for local development.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQaGlapfxHVRo0aVriq-cZ3TgVzN-3ra8',
    appId: '1:196627223703:ios:ec8c03320d834b2fc5c5d2',
    messagingSenderId: '196627223703',
    projectId: 'us-app-4bf30',
    storageBucket: 'us-app-4bf30.firebasestorage.app',
    iosBundleId: 'com.us.app.usApp',
  );
}
